### ISSUE TITLE
type at point?

### ISSUE THREAD

**Issue by m4b** [vibhavp/emacs-lsp#25]
Sometimes I just want to see the type at point.

`textDocument/hover` will provide this information if the element is undocumented.  If it has lots of documentation, this is lost in the gutter.

If possible I would like an interactive method to:

1. allow keybindings to call when I want (as a longtime merlin user, C-c C-t is bound in muscle memory to give me the type of some variable/function in OCaml)
2. only receive the variable/field/function/whatever's type at the current point.

**Comment by m4b** [comment]
i think this could be implemented by a call to `textDocument/signatureHelp`?

**Comment by vibhavp** [comment]
Wouldn't that work only for functions? A way to manually invoke eldoc would
still be preferable, as you earlier mentioned.

On Fri, 20 Jan 2017, 11:19 m4b, <notifications@github.com> wrote:

i think this could be implemented by a call to textDocument/signatureHelp?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/vibhavp/emacs-lsp/issues/25#issuecomment-273983410>,
or mute
the thread

**Comment by m4b** [comment]
Hmm, yea you might be right, I'd have to check what the spec says, but its likely it only applies to functions :/

**Comment by Hi-Angel** [comment]
To future readers: I think the current function for that is `lsp-describe-thing-at-point`.

It's not quite the code that solved the issue, that one was renamed and moved a few times and as of writing the words it ended up being a function `lsp-eldoc-function`. However, it lacks "interactive" declaration, so calling it from <kbd>M</kbd>+<kbd>x</kbd> or binding to a function is not possible.

That said, at least in PureScript mode the command `lsp-describe-thing-at-point` does show the type. It's not as useful as I'd like because it only works for stuff that was declared somewhere at the top-level — applying to local variables result in "No content at point". But I presume it is the `purescript-language-server` deficiency rather than the mode having to do anything with that.
